apiVersion: v1
kind: Namespace
metadata:
  name: hotrod-demo
---
apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: hotrod
    app.kubernetes.io/instance: ackstorm-hotrod-demo
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/version: 1.53.0
    helm.sh/chart: jaeger-3.0.4
  name: hotrod-demo-hotrod
  namespace: hotrod-demo
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: hotrod
    app.kubernetes.io/instance: ackstorm-hotrod-demo
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/version: 1.53.0
    helm.sh/chart: jaeger-3.0.4
  name: hotrod-demo-hotrod
  namespace: hotrod-demo
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/component: hotrod
    app.kubernetes.io/instance: ackstorm-hotrod-demo
    app.kubernetes.io/name: jaeger
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: hotrod
    app.kubernetes.io/instance: ackstorm-hotrod-demo
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/version: 1.53.0
    helm.sh/chart: jaeger-3.0.4
  name: hotrod-demo-hotrod
  namespace: hotrod-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: hotrod
      app.kubernetes.io/instance: ackstorm-hotrod-demo
      app.kubernetes.io/name: jaeger
  template:
    metadata:
      labels:
        app.kubernetes.io/component: hotrod
        app.kubernetes.io/instance: ackstorm-hotrod-demo
        app.kubernetes.io/name: jaeger
    spec:
      containers:
      - args:
        - all
        - --otel-exporter=otlp
        env:
        - name: JAEGER_AGENT_HOST
          value: hotrod-demo-agent
        - name: JAEGER_AGENT_PORT
          value: "6831"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://opentelemetry-peer-collector.observability-peer.svc:4318
        image: jaegertracing/example-hotrod:1.53.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /
            port: http
        name: hotrod-demo-hotrod
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: http
        resources: {}
        securityContext: {}
      securityContext: {}
      serviceAccountName: hotrod-demo-hotrod
