apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: ackstorm-opencost
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: opencost
    app.kubernetes.io/part-of: opencost
    app.kubernetes.io/version: 1.110.0
    helm.sh/chart: opencost-1.37.0
  name: opencost-peer
  namespace: observability-peer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: ackstorm-opencost
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: opencost
    app.kubernetes.io/part-of: opencost
    app.kubernetes.io/version: 1.110.0
    helm.sh/chart: opencost-1.37.0
  name: opencost-peer
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - deployments
  - nodes
  - pods
  - services
  - resourcequotas
  - replicationcontrollers
  - limitranges
  - persistentvolumeclaims
  - persistentvolumes
  - namespaces
  - endpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - daemonsets
  - deployments
  - replicasets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  - deployments
  - daemonsets
  - replicasets
  verbs:
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: ackstorm-opencost
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: opencost
    app.kubernetes.io/part-of: opencost
    app.kubernetes.io/version: 1.110.0
    helm.sh/chart: opencost-1.37.0
  name: opencost-peer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: opencost-peer
subjects:
- kind: ServiceAccount
  name: opencost-peer
  namespace: observability-peer
---
apiVersion: v1
data:
  CLOUD_PROVIDER_API_KEY: QUl6YVN5RDI5Ykd4bUhBVkVPQll0Z2Q4c1lNMmdNMmVrZnhRWDRV
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: ackstorm-opencost
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: opencost
    app.kubernetes.io/part-of: opencost
    app.kubernetes.io/version: 1.110.0
    helm.sh/chart: opencost-1.37.0
  name: opencost-peer
  namespace: observability-peer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: ackstorm-opencost
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: opencost
    app.kubernetes.io/part-of: opencost
    app.kubernetes.io/version: 1.110.0
    helm.sh/chart: opencost-1.37.0
  name: opencost-peer
  namespace: observability-peer
spec:
  ports:
  - name: http
    port: 9003
    targetPort: 9003
  - name: http-ui
    port: 9090
    targetPort: 9090
  selector:
    app.kubernetes.io/instance: ackstorm-opencost
    app.kubernetes.io/name: opencost
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: ackstorm-opencost
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: opencost
    app.kubernetes.io/part-of: opencost
    app.kubernetes.io/version: 1.110.0
    helm.sh/chart: opencost-1.37.0
  name: opencost-peer
  namespace: observability-peer
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: ackstorm-opencost
      app.kubernetes.io/name: opencost
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: ackstorm-opencost
        app.kubernetes.io/name: opencost
    spec:
      containers:
      - args: null
        env:
        - name: LOG_LEVEL
          value: info
        - name: CUSTOM_COST_ENABLED
          value: "false"
        - name: KUBECOST_NAMESPACE
          value: observability-peer
        - name: API_PORT
          value: "9003"
        - name: PROMETHEUS_SERVER_ENDPOINT
          value: http://prometheus-operated.observability-peer.svc.cluster.local:9090
        - name: CLOUD_PROVIDER_API_KEY
          valueFrom:
            secretKeyRef:
              key: CLOUD_PROVIDER_API_KEY
              name: opencost-peer
        - name: CLUSTER_ID
          value: ${PEER_ID}
        - name: DATA_RETENTION_DAILY_RESOLUTION_DAYS
          value: "15"
        - name: CLOUD_COST_ENABLED
          value: "false"
        - name: CLOUD_COST_MONTH_TO_DATE_INTERVAL
          value: "6"
        - name: CLOUD_COST_REFRESH_RATE_HOURS
          value: "6"
        - name: CLOUD_COST_QUERY_WINDOW_DAYS
          value: "7"
        - name: CLOUD_COST_RUN_WINDOW_DAYS
          value: "3"
        - name: PROM_CLUSTER_ID_LABEL
          value: cluster
        image: ghcr.io/opencost/opencost:1.110.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 12
          httpGet:
            path: /healthz
            port: 9003
          initialDelaySeconds: 60
          periodSeconds: 10
        name: opencost-peer
        ports:
        - containerPort: 9003
          name: http
        readinessProbe:
          failureThreshold: 12
          httpGet:
            path: /healthz
            port: 9003
          initialDelaySeconds: 60
          periodSeconds: 10
        resources:
          limits:
            cpu: 999m
            memory: 144Mi
          requests:
            cpu: 99m
            memory: 144Mi
        startupProbe:
          failureThreshold: 30
          httpGet:
            path: /healthz
            port: 9003
          initialDelaySeconds: 10
          periodSeconds: 5
      - env:
        - name: API_PORT
          value: "9003"
        - name: UI_PORT
          value: "9090"
        image: ghcr.io/opencost/opencost-ui:1.110.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 9090
          initialDelaySeconds: 30
          periodSeconds: 10
        name: opencost-ui
        ports:
        - containerPort: 9090
          name: http-ui
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 9090
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          limits:
            cpu: 999m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 100Mi
      serviceAccountName: opencost-peer
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app.kubernetes.io/name: opencost-peer
  name: opencost-peer
  namespace: observability-peer
spec:
  groups:
  - name: opencost-peer
    rules:
    - alert: OpenCostNotRunning
      annotations:
        description: OpenCost is not running
        summary: OpenCost is not running
      expr: absent(up{job="opencost-peer"}) > 0
      for: 15m
      labels:
        severity: major
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/instance: ackstorm-opencost
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: opencost
    app.kubernetes.io/part-of: opencost
    app.kubernetes.io/version: 1.110.0
    helm.sh/chart: opencost-1.37.0
  name: opencost-peer
  namespace: observability-peer
spec:
  endpoints:
  - honorLabels: true
    interval: 30s
    path: /metrics
    port: http
    scheme: http
    scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
    - observability-peer
  selector:
    matchLabels:
      app.kubernetes.io/instance: ackstorm-opencost
      app.kubernetes.io/name: opencost
