apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: ackstorm-reloader
    meta.helm.sh/release-namespace: observability-peer
  labels:
    app: reloader-peer
    app.kubernetes.io/managed-by: Helm
    chart: reloader-1.0.97
    heritage: Helm
    release: ackstorm-reloader
  name: reloader-peer
  namespace: observability-peer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    meta.helm.sh/release-name: ackstorm-reloader
    meta.helm.sh/release-namespace: observability-peer
  labels:
    app: reloader-peer
    app.kubernetes.io/managed-by: Helm
    chart: reloader-1.0.97
    heritage: Helm
    release: ackstorm-reloader
  name: reloader-peer-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - statefulsets
  verbs:
  - list
  - get
  - update
  - patch
- apiGroups:
  - extensions
  resources:
  - deployments
  - daemonsets
  verbs:
  - list
  - get
  - update
  - patch
- apiGroups:
  - batch
  resources:
  - cronjobs
  verbs:
  - list
  - get
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    meta.helm.sh/release-name: ackstorm-reloader
    meta.helm.sh/release-namespace: observability-peer
  labels:
    app: reloader-peer
    app.kubernetes.io/managed-by: Helm
    chart: reloader-1.0.97
    heritage: Helm
    release: ackstorm-reloader
  name: reloader-peer-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: reloader-peer-role
subjects:
- kind: ServiceAccount
  name: reloader-peer
  namespace: observability-peer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    meta.helm.sh/release-name: ackstorm-reloader
    meta.helm.sh/release-namespace: observability-peer
  labels:
    app: reloader-peer
    app.kubernetes.io/managed-by: Helm
    chart: reloader-1.0.97
    group: com.stakater.platform
    heritage: Helm
    provider: stakater
    release: ackstorm-reloader
    version: v1.0.97
  name: reloader-peer
  namespace: observability-peer
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: reloader-peer
      release: ackstorm-reloader
  template:
    metadata:
      labels:
        app: reloader-peer
        app.kubernetes.io/managed-by: Helm
        chart: reloader-1.0.97
        group: com.stakater.platform
        heritage: Helm
        provider: stakater
        release: ackstorm-reloader
        version: v1.0.97
    spec:
      containers:
      - args:
        - --namespace-selector=observability-peer
        image: ghcr.io/stakater/reloader:v1.0.97
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /live
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: reloader-peer
        ports:
        - containerPort: 9090
          name: http
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /metrics
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        securityContext: {}
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: reloader-peer
