apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: ackstorm-opencost-exporter
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: prometheus-opencost-exporter
    app.kubernetes.io/version: 1.108.0
    helm.sh/chart: prometheus-opencost-exporter-0.1.1
  name: opencost-exporter-peer
  namespace: observability-peer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: ackstorm-opencost-exporter
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: prometheus-opencost-exporter
    app.kubernetes.io/version: 1.108.0
    helm.sh/chart: prometheus-opencost-exporter-0.1.1
  name: opencost-exporter-peer
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - deployments
  - nodes
  - pods
  - services
  - resourcequotas
  - replicationcontrollers
  - limitranges
  - persistentvolumeclaims
  - persistentvolumes
  - namespaces
  - endpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - daemonsets
  - deployments
  - replicasets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  - deployments
  - daemonsets
  - replicasets
  verbs:
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: ackstorm-opencost-exporter
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: prometheus-opencost-exporter
    app.kubernetes.io/version: 1.108.0
    helm.sh/chart: prometheus-opencost-exporter-0.1.1
  name: opencost-exporter-peer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: opencost-exporter-peer
subjects:
- kind: ServiceAccount
  name: opencost-exporter-peer
  namespace: observability-peer
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9003"
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/instance: ackstorm-opencost-exporter
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: prometheus-opencost-exporter
    app.kubernetes.io/version: 1.108.0
    helm.sh/chart: prometheus-opencost-exporter-0.1.1
  name: opencost-exporter-peer
  namespace: observability-peer
spec:
  ports:
  - name: http
    port: 9003
    targetPort: 9003
  selector:
    app.kubernetes.io/instance: ackstorm-opencost-exporter
    app.kubernetes.io/name: prometheus-opencost-exporter
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: ackstorm-opencost-exporter
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: prometheus-opencost-exporter
    app.kubernetes.io/version: 1.108.0
    helm.sh/chart: prometheus-opencost-exporter-0.1.1
  name: opencost-exporter-peer
  namespace: observability-peer
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: ackstorm-opencost-exporter
      app.kubernetes.io/name: prometheus-opencost-exporter
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: ackstorm-opencost-exporter
        app.kubernetes.io/name: prometheus-opencost-exporter
    spec:
      containers:
      - env:
        - name: PROMETHEUS_SERVER_ENDPOINT
          value: http://prometheus-operated.observability-peer.svc:9090
        - name: CLOUD_PROVIDER_API_KEY
          value: AIzaSyD29bGxmHAVEOBYtgd8sYM2gM2ekfxQX4U
        - name: CLUSTER_ID
          value: ${PEER_ID}
        - name: LOG_LEVEL
          value: info
        image: quay.io/kubecost1/kubecost-cost-model:prod-1.108.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 12
          httpGet:
            path: /healthz
            port: 9003
          initialDelaySeconds: 60
          periodSeconds: 10
        name: opencost-exporter-peer
        ports:
        - containerPort: 9003
          name: http
        readinessProbe:
          failureThreshold: 12
          httpGet:
            path: /healthz
            port: 9003
          initialDelaySeconds: 60
          periodSeconds: 10
        resources:
          limits:
            cpu: 999m
            memory: 144Mi
          requests:
            cpu: 99m
            memory: 144Mi
      serviceAccountName: opencost-exporter-peer
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app.kubernetes.io/name: opencost-peer
  name: opencost-peer
  namespace: observability-peer
spec:
  groups:
  - name: opencost-peer
    rules:
    - alert: OpenCostNotRunning
      annotations:
        description: OpenCost is not running
        summary: OpenCost is not running
      expr: absent(up{job="opencost-peer"}) > 0
      for: 15m
      labels:
        severity: major
