apiVersion: v1
kind: Namespace
metadata:
  name: otel-demo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: ackstorm-otel-demo-backend
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: otel-demo-backend
    app.kubernetes.io/version: 0.1.13
    helm.sh/chart: otel-demo-backend-0.1.12
  name: otel-demo-backend
  namespace: otel-demo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: ackstorm-otel-demo-frontend
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: otel-demo-frontend
    app.kubernetes.io/version: 0.1.14
    helm.sh/chart: otel-demo-frontend-0.1.14
  name: otel-demo-frontend
  namespace: otel-demo
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: otel-demo-backend
    app.kubernetes.io/instance: ackstorm-otel-demo-backend
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: otel-demo-backend
    app.kubernetes.io/version: 0.1.13
    helm.sh/chart: otel-demo-backend-0.1.12
  name: otel-demo-backend
  namespace: otel-demo
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http-metrics
  selector:
    app.kubernetes.io/instance: ackstorm-otel-demo-backend
    app.kubernetes.io/name: otel-demo-backend
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: otel-demo-frontend
    app.kubernetes.io/instance: ackstorm-otel-demo-frontend
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: otel-demo-frontend
    app.kubernetes.io/version: 0.1.14
    helm.sh/chart: otel-demo-frontend-0.1.14
  name: otel-demo-frontend
  namespace: otel-demo
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http-metrics
  selector:
    app.kubernetes.io/instance: ackstorm-otel-demo-frontend
    app.kubernetes.io/name: otel-demo-frontend
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: ackstorm-otel-demo-backend
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: otel-demo-backend
    app.kubernetes.io/version: 0.1.13
    helm.sh/chart: otel-demo-backend-0.1.12
  name: otel-demo-backend
  namespace: otel-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: ackstorm-otel-demo-backend
      app.kubernetes.io/name: otel-demo-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: ackstorm-otel-demo-backend
        app.kubernetes.io/name: otel-demo-backend
    spec:
      containers:
      - env:
        - name: BACKEND_LISTEN
          value: 0.0.0.0:80
        - name: JAEGER_ENDPOINT
          value: http://opentelemetry-peer-collector.observability-peer.svc:14268/api/traces
        image: jtyr/otel-demo:backend-0.1.13
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /metrics
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
        name: app
        ports:
        - containerPort: 80
          name: http-metrics
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /metrics
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        resources: {}
        securityContext: {}
      securityContext: {}
      serviceAccountName: otel-demo-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: ackstorm-otel-demo-frontend
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: otel-demo-frontend
    app.kubernetes.io/version: 0.1.14
    helm.sh/chart: otel-demo-frontend-0.1.14
  name: otel-demo-frontend
  namespace: otel-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: ackstorm-otel-demo-frontend
      app.kubernetes.io/name: otel-demo-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: ackstorm-otel-demo-frontend
        app.kubernetes.io/name: otel-demo-frontend
    spec:
      containers:
      - env:
        - name: BACKEND_ENDPOINT
          value: http://otel-demo-backend/api/main
        - name: FRONTEND_LISTEN
          value: 0.0.0.0:80
        - name: JAEGER_ENDPOINT
          value: http://opentelemetry-peer-collector.observability-peer.svc:14268/api/traces
        image: jtyr/otel-demo:frontend-0.1.14
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /metrics
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
        name: app
        ports:
        - containerPort: 80
          name: http-metrics
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /metrics
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        resources: {}
        securityContext: {}
      securityContext: {}
      serviceAccountName: otel-demo-frontend
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: kps
  name: otel-demo-backend
  namespace: otel-demo
spec:
  endpoints:
  - path: /metrics
    port: http
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: otel-demo-backend
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: kps
  name: otel-demo-frontend
  namespace: otel-demo
spec:
  endpoints:
  - path: /metrics
    port: http
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: otel-demo-frontend
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    helm.sh/hook: test
  labels:
    app.kubernetes.io/instance: ackstorm-otel-demo-backend
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: otel-demo-backend
    app.kubernetes.io/version: 0.1.13
    helm.sh/chart: otel-demo-backend-0.1.12
  name: otel-demo-backend-test-connection
  namespace: otel-demo
spec:
  containers:
  - args:
    - otel-demo-backend:80
    command:
    - wget
    image: busybox
    name: wget
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    helm.sh/hook: test
  labels:
    app.kubernetes.io/instance: ackstorm-otel-demo-frontend
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: otel-demo-frontend
    app.kubernetes.io/version: 0.1.14
    helm.sh/chart: otel-demo-frontend-0.1.14
  name: otel-demo-frontend-test-connection
  namespace: otel-demo
spec:
  containers:
  - args:
    - otel-demo-frontend:80
    command:
    - wget
    image: busybox
    name: wget
  restartPolicy: Never
